spring.application.name=wehear

server.port=${PORT:8080}

spring.datasource.url=jdbc:mysql://yamanote.proxy.rlwy.net:52984/wehear_db?useSSL=false&serverTimezone=Asia/Ho_Chi_Minh&allowPublicKeyRetrieval=true

spring.datasource.username=root

spring.datasource.password=UUwSBtPNOpGtvSzGmvtUIioZHXbWCeja
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jackson.time-zone=Asia/Ho_Chi_Minh
spring.jackson.date-format=yyyy-MM-dd HH:mm:ss

# Mail Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# JWT Configuration
jwt.secret=${JWT_SECRET}
jwt.expiration=86400000

# File Upload Configuration
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

# Gemini AI Configuration
google.ai.api.key=${GOOGLE_AI_API_KEY}
google.ai.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent

# Cloudinary Configuration
cloudinary.cloud_name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api_key=${CLOUDINARY_API_KEY}
cloudinary.api_secret=${CLOUDINARY_API_SECRET}
